/** Shared test fixture: a complete snapshot as the Rust view model serializes it. */
export function snapshotFixture(): unknown {
  return {
    run: {
      id: "run_0412aa",
      state: "running",
      stop_condition: null,
      iterations: 1,
      paused_ms: 0,
      created_at: "2026-10-04T14:00:00Z",
      updated_at: "2026-10-04T14:04:17Z",
    },
    goal: {
      question: "Which mechanisms could explain acquired resistance?",
      mode: "campaign",
      revision: 0,
      deliverables: ["research report"],
      budget: {
        max_model_calls: 200,
        max_iterations: 4,
        wall_clock_secs: 3600,
        max_debate_turns: 5,
        max_tokens: 2000000,
      },
    },
    plan: {
      revision: 0,
      roles: ["generation", "reflection", "ranking"],
      methods: ["grounded generation"],
      rationale: "campaign plan",
    },
    agents: [
      {
        role: "supervisor",
        state: "thinking",
        counts: {
          pending: 1,
          blocked: 0,
          running: 0,
          waiting_for_human: 0,
          completed: 2,
          failed: 0,
          cancelled: 0,
          uncertain: 0,
        },
        current: null,
        last_finished: null,
        assignments: [
          { role: "generation", open: 3, running: 1, latest_strategy: "literature" },
        ],
      },
      {
        role: "generation",
        state: "thinking",
        counts: {
          pending: 2,
          blocked: 0,
          running: 1,
          waiting_for_human: 0,
          completed: 4,
          failed: 0,
          cancelled: 0,
          uncertain: 0,
        },
        current: {
          strategy: "literature",
          state: "running",
          attempts: 1,
          started_at: "2026-10-04T14:04:00Z",
          finished_at: null,
          error: null,
        },
        last_finished: null,
        assignments: null,
      },
    ],
    stats: {
      items: 13,
      reviews: 4,
      matches: 34,
      clusters: 4,
      sources: 41,
      works: 0,
      searches: 0,
      pending_approvals: 0,
      workers_busy: 3,
      workers_total: 4,
      leader: {
        item_id: "item_h7",
        title: "XBP1 splicing escape",
        rating: 1412.2,
        matches_played: 9,
      },
    },
    usage: {
      model_calls: 12,
      tokens: 48000,
      tool_executions: 0,
      reserved_calls: 2,
      reserved_tokens: 0,
      reserved_tool_executions: 0,
      cost_usd: null,
      cost_partially_unknown: false,
    },
    items: [
      {
        id: "item_h7",
        kind: "hypothesis",
        title: "XBP1 splicing escape",
        disposition: "active",
        assessment: "plausible",
        rating: 1412.2,
        matches_played: 9,
        stale_rating: false,
        review_count: 3,
      },
    ],
  };
}
